### ISSUE TITLE
How to transfer to Switch?

### ISSUE THREAD

**Issue by winterlite** [arrow2nd/sb4-extension#3]
Hello, I am wondering how to transfer these files to the Switch.

**Comment by arrow2nd** [comment]
There is a way to create and transfer dedicated hardware.

You can find instructions on how to make and use it at the following site, though it is in Japanese.

> http://rei.to/petit4send.html

**Comment by winterlite** [comment]
Thanks!

**Comment by winterlite** [comment]
Oh, he has an English version! http://rei.to/petit4send_en.html
